// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD7GAxupkgEwVFfpwNBmkRNX7sa8pSN0bY',
    appId: '1:78295280952:web:3d9a350e4ee1a64d58a5cd',
    messagingSenderId: '78295280952',
    projectId: 'pelanggan-f515f',
    authDomain: 'pelanggan-f515f.firebaseapp.com',
    storageBucket: 'pelanggan-f515f.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCEGyWOaNu977zAWLDRjBrl-4mFEjgHhjQ',
    appId: '1:78295280952:android:09a57484bdddc5f558a5cd',
    messagingSenderId: '78295280952',
    projectId: 'pelanggan-f515f',
    storageBucket: 'pelanggan-f515f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDtpj-2Gv2FzJ4Pr57mOQfkmfhj8T33cxI',
    appId: '1:78295280952:ios:e437b64a7441e76a58a5cd',
    messagingSenderId: '78295280952',
    projectId: 'pelanggan-f515f',
    storageBucket: 'pelanggan-f515f.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDtpj-2Gv2FzJ4Pr57mOQfkmfhj8T33cxI',
    appId: '1:78295280952:ios:e437b64a7441e76a58a5cd',
    messagingSenderId: '78295280952',
    projectId: 'pelanggan-f515f',
    storageBucket: 'pelanggan-f515f.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD7GAxupkgEwVFfpwNBmkRNX7sa8pSN0bY',
    appId: '1:78295280952:web:2ed4dd751ab1099058a5cd',
    messagingSenderId: '78295280952',
    projectId: 'pelanggan-f515f',
    authDomain: 'pelanggan-f515f.firebaseapp.com',
    storageBucket: 'pelanggan-f515f.firebasestorage.app',
  );
}
